# 百度AI接口配置
baidu.api.key=rNSO0atxN8f1JyeKl02duJMp
baidu.api.secret=9BTkLXQb7Dd8s8tlCCMyIWXXIR1t75aL

# 文件上传配置
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# H2嵌入式数据库配置
spring.datasource.url=jdbc:h2:file:./data/waste_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA配置
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2控制台（可选，开发时查看数据库）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
